# Generated by Django 2.0 on 2018-05-28 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constant', '0002_clubtype_puttingaimrange_puttingdistrange'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubBag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.PositiveSmallIntegerField(choices=[(1, 'No confidence'), (2, 'Slight confidence'), (3, 'Neutral'), (4, 'Fair confidence'), (5, 'Great confidence')])),
                ('avg_dist', models.PositiveIntegerField()),
                ('club_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constant.ClubType')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-avg_dist',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='clubbag',
            unique_together={('club_type', 'owner')},
        ),
    ]
