# Generated by Django 2.0 on 2018-05-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180528_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubbag',
            name='club_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='clubbag',
            name='club_type',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='clubbag',
            unique_together={('owner', 'club_type', 'club_name')},
        ),
    ]
