# Generated by Django 2.0.3 on 2019-09-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180529_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creation_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Creation Time'),
        ),
    ]
