# Generated by Django 2.0 on 2018-05-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AimDiffRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.IntegerField()),
                ('step', models.PositiveIntegerField()),
                ('max', models.IntegerField()),
                ('mode', models.CharField(choices=[('yard', 'Yard'), ('feet', 'Feet')], default='yard', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AimValueRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64, unique=True)),
                ('value', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ('value',),
            },
        ),
        migrations.CreateModel(
            name='DistanceDiffRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.IntegerField()),
                ('step', models.PositiveIntegerField()),
                ('max', models.IntegerField()),
                ('mode', models.CharField(choices=[('yard', 'Yard'), ('feet', 'Feet')], default='yard', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeetBucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.IntegerField(unique=True, verbose_name='from')),
                ('max', models.IntegerField(unique=True, verbose_name='to')),
                ('percent', models.IntegerField(verbose_name='percent (%)')),
            ],
            options={
                'ordering': ('min',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShotImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('shape', models.ImageField(upload_to='shotshapes/', verbose_name='Shot Shape')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TrajectoryDiffRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, unique=True)),
                ('value', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('value',),
            },
        ),
        migrations.CreateModel(
            name='TrajectoryValueRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
                ('value', models.IntegerField()),
                ('type', models.CharField(choices=[('long', 'Long'), ('putting', 'Putting'), ('chip', 'Around the Green (chip)'), ('pitch', 'Around the Green (pitch)')], default='long', max_length=10)),
            ],
            options={
                'ordering': ('type',),
            },
        ),
        migrations.CreateModel(
            name='YardBucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.IntegerField(unique=True, verbose_name='from')),
                ('max', models.IntegerField(unique=True, verbose_name='to')),
                ('percent', models.IntegerField(verbose_name='percent (%)')),
            ],
            options={
                'ordering': ('min',),
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='yardbucket',
            unique_together={('min', 'max')},
        ),
        migrations.AlterUniqueTogether(
            name='trajectoryvaluerange',
            unique_together={('type', 'description')},
        ),
        migrations.AlterUniqueTogether(
            name='feetbucket',
            unique_together={('min', 'max')},
        ),
    ]
