# Generated by Django 2.0 on 2018-05-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constant', '0002_clubtype_puttingaimrange_puttingdistrange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubtype',
            options={'ordering': ('id',)},
        ),
    ]
