# Generated by Django 2.0 on 2018-04-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billinginfo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plan_id', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
