# Generated by Django 2.0 on 2018-04-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20180418_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginfo',
            name='subscription_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
