# Generated by Django 2.0 on 2018-05-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_billinginfo_subscription_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginfo',
            name='subscription_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
