# Generated by Django 2.0.3 on 2019-01-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_auto_20190129_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginfo',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='exp_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='exp_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
