# Generated by Django 2.0 on 2018-05-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deltashotreport',
            name='aim',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='deltashotreport',
            name='trajectory',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='practice',
            name='practice_type',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Full Swing (Gated Random)'), (11, 'Serial'), (12, 'Block'), (13, 'Warmup'), (20, 'Putting (Gated Random )'), (21, 'Putting (Standard)'), (22, 'Putting (Within 3 Feet)'), (23, 'Putting (6 Foot Challenge)'), (30, 'Around the green (Chip)'), (31, 'Around the green (Pitch)')]),
        ),
    ]
