# Generated by Django 2.0 on 2018-05-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180518_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deltashotreport',
            name='hit',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Hit'), (0, 'Miss')]),
        ),
    ]
