# Generated by Django 2.0 on 2018-05-28 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constant', '0002_clubtype_puttingaimrange_puttingdistrange'),
        ('core', '0003_auto_20180518_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='deltashotreport',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='constant.ClubType'),
        ),
        migrations.AddField(
            model_name='practice',
            name='max_dist',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='min_dist',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deltashotreport',
            name='trajectory',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='practice_type',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Full Swing (Gated Random)'), (11, 'Serial'), (12, 'Block'), (13, 'Warmup'), (14, 'Custom Practice'), (20, 'Putting (Gated Random )'), (21, 'Putting (Standard)'), (22, 'Putting (Within 3 Feet)'), (23, 'Putting (6 Foot Challenge)'), (30, 'Around the green (Chip)'), (31, 'Around the green (Pitch)')]),
        ),
    ]
