# Generated by Django 2.0 on 2018-05-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180528_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoreshotreport',
            options={'ordering': ('reported_at',)},
        ),
        migrations.AlterField(
            model_name='practice',
            name='max_dist',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='min_dist',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='practice_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Full Swing (Gated Random)'), (1, 'Serial'), (2, 'Block'), (3, 'Warmup'), (8, 'Custom Practice'), (4, 'Putting (Gated Random )'), (5, 'Putting (Standard)'), (22, 'Putting (Within 3 Feet)'), (23, 'Putting (6 Foot Challenge)'), (6, 'Around the green (Chip)'), (7, 'Around the green (Pitch)')]),
        ),
    ]
