# Generated by Django 2.0 on 2018-05-28 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180528_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoreshotreport',
            options={'ordering': ('practice', 'reported_at')},
        ),
    ]
