# Generated by Django 2.0.3 on 2018-10-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180529_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='practice_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Full Swing (Gated Random)'), (1, 'Serial'), (2, 'Block'), (3, 'Warmup'), (8, 'Custom Practice'), (4, 'Putting (Gated Random )'), (5, 'Putting (Standard)'), (9, 'Putting (Custom)'), (22, 'Putting (Within 3 Feet)'), (23, 'Putting (6 Foot Challenge)'), (6, 'Around the green (Chip)'), (7, 'Around the green (Pitch)')]),
        ),
    ]
